llvm: add support for rebuild and PGO
shinchiro/mpv-winbuild-cmake pull request #632
Opened 2024-03-13 06:42 UTC by Andarwinux

This reduces the first CI build time by 20 minutes. For cached builds, the build system itself and ccache are the biggest bottlenecks. Local users can also easily try LLVM main branch and update LLVM at any time without waiting hours.

2024-03-16 16:23 UTC, shinchiro commented on toolchain/llvm/llvm.cmake
> +        "-DLLVM_THINLTO_CACHE_PATH='${CMAKE_INSTALL_PREFIX}/llvm-thinlto'"
Does CI will save this `llvm-thinlto` dir?

2024-03-16 16:29 UTC, shinchiro commented
> This reduces the first CI build time by 20 minutes. For cached builds, the build system itself and ccache are the biggest bottlenecks. 

How about compiling with ccache disabled?

2024-03-19 18:49 UTC, zhongfly commented
https://releases.llvm.org/18.1.0/tools/clang/docs/UsersManual.html#profiling-with-instrumentation
According to the documentation, my understanding of the steps to use pgo is as follows, please correct me if there are any errors:
1. build llvm with `-fprofile-generate` flag.
2. run llvm with `LLVM_PROFILE_FILE` environment variable, profile data will written to `LLVM_PROFILE_FILE`.`LLVM_PROFILE_FILE` will override `-fprofile-generate=<dir>` setting, so no need to specify profile data dir in  step 1.
3. use profile data to rebuild llvm.I'm not sure if `-fprofile-use` and `-fprofile-generate` can be enabled at the same time, but I'm guessing they can.

2024-03-20 01:45 UTC, zhongfly commented
> -fprofile-use and -fprofile-generate are mutually exclusive options.

I haven't found any documentation that says them can't be enabled at the same time, I'll try it later.

2024-03-20 06:10 UTC, zhongfly commented
> There does exist another PGO that supports and requires both generate and use, called CSPGO, but that requires three builds, which I haven't tried.

I'm wondering if there's a way to continually optimize iteratively using PGO, currently seems to be possible by continually merging profile data and then building CSPGO?

2024-03-20 07:55 UTC, zhongfly requested changes

2024-03-20 07:55 UTC, zhongfly commented on toolchain/llvm/llvm-compiler.in
> +    if [ "@LLVM_ENABLE_PGO@" == "GEN" ] || [ "@LLVM_ENABLE_PGO@" == "CSGEN" ]; then
`if [[ -n "@LLVM_PROFILE_DATA_DIR@" ]]; then`


When training llvm, `LLVM_ENABLE_PGO` is meaningless, no need to set it to `GEN` or `CSGEN`.
 After this modification, training LLVM when building toolchain or packages does not require additional setting of cmake variables. And just set `LLVM_PROFILE_DATA_DIR` when you need to override the default profile data location.

2024-03-20 08:24 UTC, zhongfly commented on toolchain/llvm/llvm-compiler.in
> +    if [ "@LLVM_ENABLE_PGO@" == "GEN" ] || [ "@LLVM_ENABLE_PGO@" == "CSGEN" ]; then
No conflict with `LLVM_PROFDATA_FILE` used with `LLVM_ENABLE_PGO=USE`.

2024-03-21 02:45 UTC, zhongfly commented
> How about compiling with ccache disabled?

Disable ccache,build mpv without any cache.
Without PGO: 1h
Training LLVM: 1.5h
With PGO: 40+min

2024-03-21 06:06 UTC, zhongfly commented
> Is this CSPGO?

No, CSPGO takes too much time and you replied earlier that the difference is not significant.

Using only the training data from building the toolchain only took 1 minute more compared to merging the data from building all the packages. So it looks like we only need to use the toolchain build to collect data.

It may take more tries to prove it, but I'm too lazy to do that.

2024-03-22 15:16 UTC, shinchiro commented on ccache_conf.in
> +max_size = 1G
Why? 500M big enough for packages building as I dont want the packages' caches grow over time in CI

2024-03-24 02:25 UTC, shinchiro commented on CMakeLists.txt
> +    set(CCACHE_DIR "${MINGW_INSTALL_PREFIX}/ccache" CACHE STRING "Directory to keep ccached data")
I dont think `CCACHE_DIR ` option will meaningful as it cannot be shared across multiple target

2024-03-24 02:29 UTC, shinchiro commented on toolchain/llvm/llvm.cmake
>          -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=OFF
Bring "-DLLVM_THINLTO_CACHE_PATH='${CMAKE_INSTALL_PREFIX}/llvm-thinlto'" before -DCMAKE_C_FLAGS line

2024-03-24 02:56 UTC, shinchiro commented on exec.in
> +export LLVM_PROFILE_FILE="/dev/null"
Why this is necessary? `LLVM_PROFILE_FILE` var only exported when  in `GEN` or `CSGEN`. When `OFF` or `USE` it will never export

2024-03-26 09:44 UTC, shinchiro commented
Disable thinlto for the CI.

2024-03-26 10:52 UTC, shinchiro commented
As usual untested on my local machine but hopefully it does not give me problem later.

2024-03-26 10:52 UTC, merged

2024-03-26 11:06 UTC, shinchiro commented
Duh, update requirement in readme too